#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'px4-ros-mas-com==0.0.0','console_scripts','listener_drone_pos'
__requires__ = 'px4-ros-mas-com==0.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('px4-ros-mas-com==0.0.0', 'console_scripts', 'listener_drone_pos')()
    )
